package gaml.additions.solvers;

import static gama.api.gaml.types.Cast.*;
import static gama.annotations.constants.IKeyword.*;
import gama.api.runtime.scope.IScope;
import gama.api.types.list.IList;
import gama.api.types.map.IMap;
import gama.api.types.matrix.IMatrix;
import gama.plugin.solvers.Constraints;
import gama.plugin.solvers.Expressions;
import gama.plugin.solvers.GamaConstraint;
import gama.plugin.solvers.GamaConstraintType;
import gama.plugin.solvers.GamaProblem;
import gama.plugin.solvers.GamaProblemType;
import gama.plugin.solvers.GamaSolution;
import gama.plugin.solvers.GamaSolutionType;
import gama.plugin.solvers.GamaVariable;
import gama.plugin.solvers.GamaVariableType;
import gama.plugin.solvers.Models;
import gama.plugin.solvers.Reals;
import gama.plugin.solvers.Searches;
import gama.plugin.solvers.Strategies;
import gama.plugin.solvers.Variables;
@SuppressWarnings({ "rawtypes", "unchecked", "unused" })

public class GamlAdditions extends gama.api.additions.AbstractGamlAdditions {
	public void initialize() throws SecurityException, NoSuchMethodException {
	initializeType();
	initializeVars();
	initializeOperator();
}public void initializeType()  {
_type("constraint",new GamaConstraintType(TM),GamaConstraint.class);
_type("problem",new GamaProblemType(TM),GamaProblem.class);
_type("solution",new GamaSolutionType(TM),GamaSolution.class);
_type("pb_variable",new GamaVariableType(TM),GamaVariable.class);
}public void initializeVars()  {
_field(GamaConstraint.class,NAME,(s, o)->((GamaConstraint)o[0]).getConstraintName(),4,GamaConstraint.class,4,0,0);
_field(GamaConstraint.class,"posted",(s, o)->((GamaConstraint)o[0]).isPosted(),3,GamaConstraint.class,3,0,0);
_field(GamaProblem.class,NAME,(s, o)->((GamaProblem)o[0]).getProblemName(),4,GamaProblem.class,4,0,0);
_field(GamaProblem.class,"nb_variables",(s, o)->((GamaProblem)o[0]).getNbVariables(),1,GamaProblem.class,1,0,0);
_field(GamaProblem.class,"nb_constraints",(s, o)->((GamaProblem)o[0]).getNbConstraints(),1,GamaProblem.class,1,0,0);
_field(GamaProblem.class,"variables",(s, o)->((GamaProblem)o[0]).getVariables(),5,GamaProblem.class,5,776002,0);
_field(GamaProblem.class,"solutions",(s, o)->((GamaProblem)o[0]).getNbSolutions(),1,GamaProblem.class,1,0,0);
_field(GamaProblem.class,"search_time",(s, o)->((GamaProblem)o[0]).getSearchTime(),2,GamaProblem.class,2,0,0);
_field(GamaProblem.class,"nodes",(s, o)->((GamaProblem)o[0]).getNodes(),1,GamaProblem.class,1,0,0);
_field(GamaProblem.class,"fails",(s, o)->((GamaProblem)o[0]).getFails(),1,GamaProblem.class,1,0,0);
_field(GamaSolution.class,"exists",(s, o)->((GamaSolution)o[0]).exists(),3,GamaSolution.class,3,0,0);
_field(GamaSolution.class,"values",(s, o)->((GamaSolution)o[0]).getValues(),10,GamaSolution.class,10,1,4);
_field(GamaVariable.class,NAME,(s, o)->((GamaVariable)o[0]).getVariableName(),4,GamaVariable.class,4,0,0);
_field(GamaVariable.class,"kind",(s, o)->((GamaVariable)o[0]).getKind(),4,GamaVariable.class,4,0,0);
_field(GamaVariable.class,"lb",(s, o)->((GamaVariable)o[0]).getLb(),1,GamaVariable.class,1,0,0);
_field(GamaVariable.class,"ub",(s, o)->((GamaVariable)o[0]).getUb(),1,GamaVariable.class,1,0,0);
_field(GamaVariable.class,"instantiated",(s, o)->((GamaVariable)o[0]).isInstantiated(),3,GamaVariable.class,3,0,0);
_field(GamaVariable.class,"value",(s, o)->((GamaVariable)o[0]).getValue(),1,GamaVariable.class,1,0,0);
}public void initializeOperator() throws SecurityException, NoSuchMethodException {
_operator(S("sub_circuit"),Constraints.class.getMethod("subCircuit",SC,LI,GamaVariable.class),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Constraints.subCircuit(s,((IList)o[0]),((GamaVariable)o[1])),F);
_operator(S("post"),Constraints.class.getMethod("post",SC,GamaProblem.class,GamaConstraint.class),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Constraints.post(s,((GamaProblem)o[0]),((GamaConstraint)o[1])),F);
_operator(S("arithm"),Constraints.class.getMethod("arithm",SC,GamaVariable.class,S,GamaVariable.class),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Constraints.arithm(s,((GamaVariable)o[0]),((String)o[1]),((GamaVariable)o[2])),F);
_operator(S("scalar"),Constraints.class.getMethod("scalar",SC,LI,LI,S,GamaVariable.class),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Constraints.scalar(s,((IList)o[0]),((IList)o[1]),((String)o[2]),((GamaVariable)o[3])),F);
_operator(S("and_all"),Constraints.class.getMethod("andAll",SC,LI),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Constraints.andAll(s,((IList)o[0])),F);
_operator(S("bin_packing"),Constraints.class.getMethod("binPacking",SC,LI,LI,LI,i),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Constraints.binPacking(s,((IList)o[0]),((IList)o[1]),((IList)o[2]),asInt(s,o[3])),F);
_operator(S("inverse_channeling"),Constraints.class.getMethod("inverseChanneling",SC,LI,LI),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Constraints.inverseChanneling(s,((IList)o[0]),((IList)o[1])),F);
_operator(S("opposite"),Constraints.class.getMethod("opposite",SC,GamaConstraint.class),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Constraints.opposite(s,((GamaConstraint)o[0])),F);
_operator(S("all_different"),Constraints.class.getMethod("allDifferent",SC,LI),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Constraints.allDifferent(s,((IList)o[0])),F);
_operator(S("global_cardinality"),Constraints.class.getMethod("globalCardinality",SC,LI,LI,LI,b),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Constraints.globalCardinality(s,((IList)o[0]),((IList)o[1]),((IList)o[2]),asBool(s,o[3])),F);
_operator(S("path"),Constraints.class.getMethod("path",SC,LI,GamaVariable.class,GamaVariable.class),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Constraints.path(s,((IList)o[0]),((GamaVariable)o[1]),((GamaVariable)o[2])),F);
_operator(S("decreasing"),Constraints.class.getMethod("decreasing",SC,LI,i),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Constraints.decreasing(s,((IList)o[0]),asInt(s,o[1])),F);
_operator(S("sorted"),Constraints.class.getMethod("sorted",SC,LI,LI),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Constraints.sorted(s,((IList)o[0]),((IList)o[1])),F);
_operator(S("increasing"),Constraints.class.getMethod("increasing",SC,LI,i),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Constraints.increasing(s,((IList)o[0]),asInt(s,o[1])),F);
_operator(S("table"),Constraints.class.getMethod("table",SC,LI,IM),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Constraints.table(s,((IList)o[0]),((IMatrix)o[1])),F);
_operator(S("tree"),Constraints.class.getMethod("tree",SC,LI,GamaVariable.class),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Constraints.tree(s,((IList)o[0]),((GamaVariable)o[1])),F);
_operator(S("post_all"),Constraints.class.getMethod("postAll",SC,LI),null,AI,LI,F,-13,776003,-13,-13,(s,o)->Constraints.postAll(s,((IList)o[0])),F);
_operator(S("not_all_equal"),Constraints.class.getMethod("notAllEqual",SC,LI),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Constraints.notAllEqual(s,((IList)o[0])),F);
_operator(S("if_then"),Constraints.class.getMethod("ifThen",SC,GamaConstraint.class,GamaConstraint.class),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Constraints.ifThen(s,((GamaConstraint)o[0]),((GamaConstraint)o[1])),F);
_operator(S("post"),Constraints.class.getMethod("post",SC,GamaConstraint.class),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Constraints.post(s,((GamaConstraint)o[0])),F);
_operator(S("circuit"),Constraints.class.getMethod("circuit",SC,LI),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Constraints.circuit(s,((IList)o[0])),F);
_operator(S("among_values"),Constraints.class.getMethod("amongValues",SC,GamaVariable.class,LI,LI),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Constraints.amongValues(s,((GamaVariable)o[0]),((IList)o[1]),((IList)o[2])),F);
_operator(S("all_different_except_0"),Constraints.class.getMethod("allDifferentExcept0",SC,LI),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Constraints.allDifferentExcept0(s,((IList)o[0])),F);
_operator(S("knapsack"),Constraints.class.getMethod("knapsack",SC,LI,GamaVariable.class,GamaVariable.class,LI,LI),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Constraints.knapsack(s,((IList)o[0]),((GamaVariable)o[1]),((GamaVariable)o[2]),((IList)o[3]),((IList)o[4])),F);
_operator(S("lex_less"),Constraints.class.getMethod("lexLess",SC,LI,LI),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Constraints.lexLess(s,((IList)o[0]),((IList)o[1])),F);
_operator(S("at_least_n_values"),Constraints.class.getMethod("atLeastNValues",SC,LI,GamaVariable.class),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Constraints.atLeastNValues(s,((IList)o[0]),((GamaVariable)o[1])),F);
_operator(S("reify"),Constraints.class.getMethod("reify",SC,GamaConstraint.class),null,AI,GamaVariable.class,F,-13,-13,-13,-13,(s,o)->Constraints.reify(s,((GamaConstraint)o[0])),F);
_operator(S("member"),Constraints.class.getMethod("member",SC,GamaVariable.class,LI),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Constraints.member(s,((GamaVariable)o[0]),((IList)o[1])),F);
_operator(S("table"),Constraints.class.getMethod("table",SC,LI,IM,b),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Constraints.table(s,((IList)o[0]),((IMatrix)o[1]),asBool(s,o[2])),F);
_operator(S("not_member"),Constraints.class.getMethod("notMember",SC,GamaVariable.class,LI),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Constraints.notMember(s,((GamaVariable)o[0]),((IList)o[1])),F);
_operator(S("arithm"),Constraints.class.getMethod("arithm",SC,GamaVariable.class,S,d),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Constraints.arithm(s,((GamaVariable)o[0]),((String)o[1]),asFloat(s,o[2])),F);
_operator(S("or_all"),Constraints.class.getMethod("orAll",SC,LI),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Constraints.orAll(s,((IList)o[0])),F);
_operator(S("lex_less_eq"),Constraints.class.getMethod("lexLessEq",SC,LI,LI),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Constraints.lexLessEq(s,((IList)o[0]),((IList)o[1])),F);
_operator(S("arithm"),Constraints.class.getMethod("arithm",SC,GamaVariable.class,S,GamaVariable.class,S,d),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Constraints.arithm(s,((GamaVariable)o[0]),((String)o[1]),((GamaVariable)o[2]),((String)o[3]),asFloat(s,o[4])),F);
_operator(S("all_equal"),Constraints.class.getMethod("allEqual",SC,LI),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Constraints.allEqual(s,((IList)o[0])),F);
_operator(S("scalar"),Constraints.class.getMethod("scalar",SC,LI,LI,S,d),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Constraints.scalar(s,((IList)o[0]),((IList)o[1]),((String)o[2]),asFloat(s,o[3])),F);
_operator(S("element"),Constraints.class.getMethod("element",SC,GamaVariable.class,LI,GamaVariable.class),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Constraints.element(s,((GamaVariable)o[0]),((IList)o[1]),((GamaVariable)o[2])),F);
_operator(S("at_most_n_values"),Constraints.class.getMethod("atMostNValues",SC,LI,GamaVariable.class),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Constraints.atMostNValues(s,((IList)o[0]),((GamaVariable)o[1])),F);
_operator(S("n_values"),Constraints.class.getMethod("nValues",SC,LI,GamaVariable.class),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Constraints.nValues(s,((IList)o[0]),((GamaVariable)o[1])),F);
_operator(S("="),Expressions.class.getMethod("eq",SC,GamaVariable.class,GamaVariable.class),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Expressions.eq(s,((GamaVariable)o[0]),((GamaVariable)o[1])),F);
_operator(S("mod"),Expressions.class.getMethod("modulo",SC,GamaVariable.class,i),null,AI,GamaVariable.class,F,-13,-13,-13,-13,(s,o)->Expressions.modulo(s,((GamaVariable)o[0]),asInt(s,o[1])),F);
_operator(S("-"),Expressions.class.getMethod("negate",SC,GamaVariable.class),null,AI,GamaVariable.class,F,-13,-13,-13,-13,(s,o)->Expressions.negate(s,((GamaVariable)o[0])),F);
_operator(S("!="),Expressions.class.getMethod("neq",SC,d,GamaVariable.class),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Expressions.neq(s,asFloat(s,o[0]),((GamaVariable)o[1])),F);
_operator(S("<="),Expressions.class.getMethod("le",SC,GamaVariable.class,d),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Expressions.le(s,((GamaVariable)o[0]),asFloat(s,o[1])),F);
_operator(S("+"),Expressions.class.getMethod("plus",SC,GamaVariable.class,d),null,AI,GamaVariable.class,F,-13,-13,-13,-13,(s,o)->Expressions.plus(s,((GamaVariable)o[0]),asFloat(s,o[1])),F);
_operator(S("+"),Expressions.class.getMethod("plus",SC,d,GamaVariable.class),null,AI,GamaVariable.class,F,-13,-13,-13,-13,(s,o)->Expressions.plus(s,asFloat(s,o[0]),((GamaVariable)o[1])),F);
_operator(S(">="),Expressions.class.getMethod("ge",SC,d,GamaVariable.class),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Expressions.ge(s,asFloat(s,o[0]),((GamaVariable)o[1])),F);
_operator(S("mod"),Expressions.class.getMethod("modulo",SC,i,GamaVariable.class),null,AI,GamaVariable.class,F,-13,-13,-13,-13,(s,o)->Expressions.modulo(s,asInt(s,o[0]),((GamaVariable)o[1])),F);
_operator(S("!="),Expressions.class.getMethod("neq",SC,GamaVariable.class,GamaVariable.class),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Expressions.neq(s,((GamaVariable)o[0]),((GamaVariable)o[1])),F);
_operator(S("^"),Expressions.class.getMethod("power",SC,GamaVariable.class,GamaVariable.class),null,AI,GamaVariable.class,F,-13,-13,-13,-13,(s,o)->Expressions.power(s,((GamaVariable)o[0]),((GamaVariable)o[1])),F);
_operator(S("<="),Expressions.class.getMethod("le",SC,d,GamaVariable.class),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Expressions.le(s,asFloat(s,o[0]),((GamaVariable)o[1])),F);
_operator(S("/"),Expressions.class.getMethod("divide",SC,d,GamaVariable.class),null,AI,GamaVariable.class,F,-13,-13,-13,-13,(s,o)->Expressions.divide(s,asFloat(s,o[0]),((GamaVariable)o[1])),F);
_operator(S("!="),Expressions.class.getMethod("neq",SC,GamaVariable.class,d),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Expressions.neq(s,((GamaVariable)o[0]),asFloat(s,o[1])),F);
_operator(S(">"),Expressions.class.getMethod("gt",SC,d,GamaVariable.class),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Expressions.gt(s,asFloat(s,o[0]),((GamaVariable)o[1])),F);
_operator(S("-"),Expressions.class.getMethod("minus",SC,d,GamaVariable.class),null,AI,GamaVariable.class,F,-13,-13,-13,-13,(s,o)->Expressions.minus(s,asFloat(s,o[0]),((GamaVariable)o[1])),F);
_operator(S("<"),Expressions.class.getMethod("lt",SC,d,GamaVariable.class),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Expressions.lt(s,asFloat(s,o[0]),((GamaVariable)o[1])),F);
_operator(S(">="),Expressions.class.getMethod("ge",SC,GamaVariable.class,d),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Expressions.ge(s,((GamaVariable)o[0]),asFloat(s,o[1])),F);
_operator(S("*"),Expressions.class.getMethod("times",SC,GamaVariable.class,GamaVariable.class),null,AI,GamaVariable.class,F,-13,-13,-13,-13,(s,o)->Expressions.times(s,((GamaVariable)o[0]),((GamaVariable)o[1])),F);
_operator(S("+"),Expressions.class.getMethod("plus",SC,GamaVariable.class,GamaVariable.class),null,AI,GamaVariable.class,F,-13,-13,-13,-13,(s,o)->Expressions.plus(s,((GamaVariable)o[0]),((GamaVariable)o[1])),F);
_operator(S("same"),Expressions.class.getMethod("same",SC,GamaVariable.class,GamaVariable.class),null,AI,b,F,-13,-13,-13,-13,(s,o)->Expressions.same(s,((GamaVariable)o[0]),((GamaVariable)o[1])),F);
_operator(S("-"),Expressions.class.getMethod("minus",SC,GamaVariable.class,d),null,AI,GamaVariable.class,F,-13,-13,-13,-13,(s,o)->Expressions.minus(s,((GamaVariable)o[0]),asFloat(s,o[1])),F);
_operator(S(">"),Expressions.class.getMethod("gt",SC,GamaVariable.class,d),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Expressions.gt(s,((GamaVariable)o[0]),asFloat(s,o[1])),F);
_operator(S("<="),Expressions.class.getMethod("le",SC,GamaVariable.class,GamaVariable.class),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Expressions.le(s,((GamaVariable)o[0]),((GamaVariable)o[1])),F);
_operator(S("/"),Expressions.class.getMethod("divide",SC,GamaVariable.class,d),null,AI,GamaVariable.class,F,-13,-13,-13,-13,(s,o)->Expressions.divide(s,((GamaVariable)o[0]),asFloat(s,o[1])),F);
_operator(S("="),Expressions.class.getMethod("eq",SC,d,GamaVariable.class),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Expressions.eq(s,asFloat(s,o[0]),((GamaVariable)o[1])),F);
_operator(S("^"),Expressions.class.getMethod("power",SC,GamaVariable.class,i),null,AI,GamaVariable.class,F,-13,-13,-13,-13,(s,o)->Expressions.power(s,((GamaVariable)o[0]),asInt(s,o[1])),F);
_operator(S("<"),Expressions.class.getMethod("lt",SC,GamaVariable.class,d),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Expressions.lt(s,((GamaVariable)o[0]),asFloat(s,o[1])),F);
_operator(S("as_table"),Expressions.class.getMethod("asTable",SC,GamaConstraint.class),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Expressions.asTable(s,((GamaConstraint)o[0])),F);
_operator(S("*"),Expressions.class.getMethod("times",SC,GamaVariable.class,d),null,AI,GamaVariable.class,F,-13,-13,-13,-13,(s,o)->Expressions.times(s,((GamaVariable)o[0]),asFloat(s,o[1])),F);
_operator(S(">"),Expressions.class.getMethod("gt",SC,GamaVariable.class,GamaVariable.class),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Expressions.gt(s,((GamaVariable)o[0]),((GamaVariable)o[1])),F);
_operator(S("*"),Expressions.class.getMethod("times",SC,d,GamaVariable.class),null,AI,GamaVariable.class,F,-13,-13,-13,-13,(s,o)->Expressions.times(s,asFloat(s,o[0]),((GamaVariable)o[1])),F);
_operator(S("<"),Expressions.class.getMethod("lt",SC,GamaVariable.class,GamaVariable.class),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Expressions.lt(s,((GamaVariable)o[0]),((GamaVariable)o[1])),F);
_operator(S("mod"),Expressions.class.getMethod("modulo",SC,GamaVariable.class,GamaVariable.class),null,AI,GamaVariable.class,F,-13,-13,-13,-13,(s,o)->Expressions.modulo(s,((GamaVariable)o[0]),((GamaVariable)o[1])),F);
_operator(S(">="),Expressions.class.getMethod("ge",SC,GamaVariable.class,GamaVariable.class),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Expressions.ge(s,((GamaVariable)o[0]),((GamaVariable)o[1])),F);
_operator(S("="),Expressions.class.getMethod("eq",SC,GamaVariable.class,d),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Expressions.eq(s,((GamaVariable)o[0]),asFloat(s,o[1])),F);
_operator(S("-"),Expressions.class.getMethod("minus",SC,GamaVariable.class,GamaVariable.class),null,AI,GamaVariable.class,F,-13,-13,-13,-13,(s,o)->Expressions.minus(s,((GamaVariable)o[0]),((GamaVariable)o[1])),F);
_operator(S("/"),Expressions.class.getMethod("divide",SC,GamaVariable.class,GamaVariable.class),null,AI,GamaVariable.class,F,-13,-13,-13,-13,(s,o)->Expressions.divide(s,((GamaVariable)o[0]),((GamaVariable)o[1])),F);
_operator(S("read_mps"),Models.class.getMethod("readMps",SC,S,S),null,AI,GamaProblem.class,F,-13,-13,-13,-13,(s,o)->Models.readMps(s,((String)o[0]),((String)o[1])),F);
_operator(S("optimize"),Models.class.getMethod("optimize",SC,GamaProblem.class),null,AI,GamaSolution.class,F,-13,-13,-13,-13,(s,o)->Models.optimize(s,((GamaProblem)o[0])),F);
_operator(S("read_mps"),Models.class.getMethod("readMps",SC,S),null,AI,GamaProblem.class,F,-13,-13,-13,-13,(s,o)->Models.readMps(s,((String)o[0])),F);
_operator(S("maximises"),Models.class.getMethod("maximises",SC,GamaProblem.class),null,AI,b,F,-13,-13,-13,-13,(s,o)->Models.maximises(s,((GamaProblem)o[0])),F);
_operator(S("objective_of"),Models.class.getMethod("objectiveOf",SC,GamaProblem.class),null,AI,S,F,-13,-13,-13,-13,(s,o)->Models.objectiveOf(s,((GamaProblem)o[0])),F);
_operator(S("real_value_of"),Models.class.getMethod("realValueOf",SC,GamaSolution.class,GamaVariable.class),null,AI,D,F,-13,-13,-13,-13,(s,o)->Models.realValueOf(s,((GamaSolution)o[0]),((GamaVariable)o[1])),F);
_operator(S("objective_value"),Models.class.getMethod("objectiveValue",SC,GamaSolution.class),null,AI,D,F,-13,-13,-13,-13,(s,o)->Models.objectiveValue(s,((GamaSolution)o[0])),F);
initializeOperator2(); 
}public void initializeOperator2() throws SecurityException, NoSuchMethodException {
_operator(S("set_precision"),Reals.class.getMethod("setPrecision",SC,GamaProblem.class,d),null,AI,GamaProblem.class,F,-13,-13,-13,-13,(s,o)->Reals.setPrecision(s,((GamaProblem)o[0]),asFloat(s,o[1])),F);
_operator(S("real_view"),Reals.class.getMethod("realView",SC,GamaVariable.class,d),null,AI,GamaVariable.class,F,-13,-13,-13,-13,(s,o)->Reals.realView(s,((GamaVariable)o[0]),asFloat(s,o[1])),F);
_operator(S("real_scalar"),Reals.class.getMethod("realScalar",SC,LI,LI,S,GamaVariable.class),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Reals.realScalar(s,((IList)o[0]),((IList)o[1]),((String)o[2]),((GamaVariable)o[3])),F);
_operator(S("real_element"),Reals.class.getMethod("realElement",SC,GamaVariable.class,LI,GamaVariable.class),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Reals.realElement(s,((GamaVariable)o[0]),((IList)o[1]),((GamaVariable)o[2])),F);
_operator(S("real_scalar"),Reals.class.getMethod("realScalar",SC,LI,LI,S,d),null,AI,GamaConstraint.class,F,-13,-13,-13,-13,(s,o)->Reals.realScalar(s,((IList)o[0]),((IList)o[1]),((String)o[2]),asFloat(s,o[3])),F);
_operator(S("all_solutions"),Searches.class.getMethod("allSolutions",SC,GamaProblem.class,i),null,AI,LI,F,-13,776004,-13,-13,(s,o)->Searches.allSolutions(s,((GamaProblem)o[0]),asInt(s,o[1])),F);
_operator(S("add_hint"),Searches.class.getMethod("addHint",SC,GamaVariable.class,i),null,AI,GamaVariable.class,F,-13,-13,-13,-13,(s,o)->Searches.addHint(s,((GamaVariable)o[0]),asInt(s,o[1])),F);
_operator(S("clear_hints"),Searches.class.getMethod("clearHints",SC,GamaProblem.class),null,AI,GamaProblem.class,F,-13,-13,-13,-13,(s,o)->Searches.clearHints(s,((GamaProblem)o[0])),F);
_operator(S("minimize"),Searches.class.getMethod("minimize",SC,GamaProblem.class,GamaVariable.class,d),null,AI,GamaSolution.class,F,-13,-13,-13,-13,(s,o)->Searches.minimize(s,((GamaProblem)o[0]),((GamaVariable)o[1]),asFloat(s,o[2])),F);
_operator(S("all_solutions"),Searches.class.getMethod("allSolutions",SC,GamaProblem.class),null,AI,LI,F,-13,776004,-13,-13,(s,o)->Searches.allSolutions(s,((GamaProblem)o[0])),F);
_operator(S("hint_from"),Searches.class.getMethod("hintFrom",SC,GamaProblem.class,GamaSolution.class),null,AI,i,F,-13,-13,-13,-13,(s,o)->Searches.hintFrom(s,((GamaProblem)o[0]),((GamaSolution)o[1])),F);
_operator(S("search"),Searches.class.getMethod("search",SC,GamaProblem.class),null,AI,GamaSolution.class,F,-13,-13,-13,-13,(s,o)->Searches.search(s,((GamaProblem)o[0])),F);
_operator(S("maximize"),Searches.class.getMethod("maximize",SC,GamaProblem.class,GamaVariable.class),null,AI,GamaSolution.class,F,-13,-13,-13,-13,(s,o)->Searches.maximize(s,((GamaProblem)o[0]),((GamaVariable)o[1])),F);
_operator(S("maximize"),Searches.class.getMethod("maximize",SC,GamaProblem.class,GamaVariable.class,d),null,AI,GamaSolution.class,F,-13,-13,-13,-13,(s,o)->Searches.maximize(s,((GamaProblem)o[0]),((GamaVariable)o[1]),asFloat(s,o[2])),F);
_operator(S("reset"),Searches.class.getMethod("reset",SC,GamaProblem.class),null,AI,GamaProblem.class,F,-13,-13,-13,-13,(s,o)->Searches.reset(s,((GamaProblem)o[0])),F);
_operator(S("search"),Searches.class.getMethod("search",SC,GamaProblem.class,d),null,AI,GamaSolution.class,F,-13,-13,-13,-13,(s,o)->Searches.search(s,((GamaProblem)o[0]),asFloat(s,o[1])),F);
_operator(S("minimize"),Searches.class.getMethod("minimize",SC,GamaProblem.class,GamaVariable.class),null,AI,GamaSolution.class,F,-13,-13,-13,-13,(s,o)->Searches.minimize(s,((GamaProblem)o[0]),((GamaVariable)o[1])),F);
_operator(S("with_conflict_ordering"),Strategies.class.getMethod("withConflictOrdering",SC,GamaProblem.class),null,AI,GamaProblem.class,F,-13,-13,-13,-13,(s,o)->Strategies.withConflictOrdering(s,((GamaProblem)o[0])),F);
_operator(S("with_best_bound"),Strategies.class.getMethod("withBestBound",SC,GamaProblem.class),null,AI,GamaProblem.class,F,-13,-13,-13,-13,(s,o)->Strategies.withBestBound(s,((GamaProblem)o[0])),F);
_operator(S("use_strategy"),Strategies.class.getMethod("useStrategy",SC,GamaProblem.class,S,LI),null,AI,GamaProblem.class,F,-13,-13,-13,-13,(s,o)->Strategies.useStrategy(s,((GamaProblem)o[0]),((String)o[1]),((IList)o[2])),F);
_operator(S("use_restarts"),Strategies.class.getMethod("useRestarts",SC,GamaProblem.class,S,i),null,AI,GamaProblem.class,F,-13,-13,-13,-13,(s,o)->Strategies.useRestarts(s,((GamaProblem)o[0]),((String)o[1]),asInt(s,o[2])),F);
_operator(S("record_nogoods"),Strategies.class.getMethod("recordNogoods",SC,GamaProblem.class),null,AI,GamaProblem.class,F,-13,-13,-13,-13,(s,o)->Strategies.recordNogoods(s,((GamaProblem)o[0])),F);
_operator(S("with_last_conflict"),Strategies.class.getMethod("withLastConflict",SC,GamaProblem.class),null,AI,GamaProblem.class,F,-13,-13,-13,-13,(s,o)->Strategies.withLastConflict(s,((GamaProblem)o[0])),F);
_operator(S("problem"),Strategies.class.getMethod("problemWithBackend",SC,S,S),null,AI,GamaProblem.class,F,-13,-13,-13,-13,(s,o)->Strategies.problemWithBackend(s,((String)o[0]),((String)o[1])),F);
_operator(S("use_strategy"),Strategies.class.getMethod("useStrategy",SC,GamaProblem.class,S),null,AI,GamaProblem.class,F,-13,-13,-13,-13,(s,o)->Strategies.useStrategy(s,((GamaProblem)o[0]),((String)o[1])),F);
_operator(S("neg_var"),Variables.class.getMethod("negVar",SC,GamaVariable.class),null,AI,GamaVariable.class,F,-13,-13,-13,-13,(s,o)->Variables.negVar(s,((GamaVariable)o[0])),F);
_operator(S("values_of"),Variables.class.getMethod("valuesOf",SC,GamaSolution.class,LI),null,AI,LI,F,-13,1,-13,-13,(s,o)->Variables.valuesOf(s,((GamaSolution)o[0]),((IList)o[1])),F);
_operator(S("set_var"),Variables.class.getMethod("setVar",SC,GamaProblem.class,S,LI,LI),null,AI,GamaVariable.class,F,-13,-13,-13,-13,(s,o)->Variables.setVar(s,((GamaProblem)o[0]),((String)o[1]),((IList)o[2]),((IList)o[3])),F);
_operator(S("arg_min_var"),Variables.class.getMethod("argMinVar",SC,LI),null,AI,GamaVariable.class,F,-13,-13,-13,-13,(s,o)->Variables.argMinVar(s,((IList)o[0])),F);
_operator(S("offset_var"),Variables.class.getMethod("offsetVar",SC,GamaVariable.class,i),null,AI,GamaVariable.class,F,-13,-13,-13,-13,(s,o)->Variables.offsetVar(s,((GamaVariable)o[0]),asInt(s,o[1])),F);
_operator(S("int_var"),Variables.class.getMethod("intVarIn",SC,GamaProblem.class,S,LI),null,AI,GamaVariable.class,F,-13,-13,-13,-13,(s,o)->Variables.intVarIn(s,((GamaProblem)o[0]),((String)o[1]),((IList)o[2])),F);
_operator(S("element_var"),Variables.class.getMethod("elementVar",SC,IM,i,GamaVariable.class),null,AI,GamaVariable.class,F,-13,-13,-13,-13,(s,o)->Variables.elementVar(s,((IMatrix)o[0]),asInt(s,o[1]),((GamaVariable)o[2])),F);
_operator(S("element_var"),Variables.class.getMethod("elementVar",SC,LI,GamaVariable.class),null,AI,GamaVariable.class,F,-13,-13,-13,-13,(s,o)->Variables.elementVar(s,((IList)o[0]),((GamaVariable)o[1])),F);
_operator(S("max_var"),Variables.class.getMethod("maxVar",SC,LI),null,AI,GamaVariable.class,F,-13,-13,-13,-13,(s,o)->Variables.maxVar(s,((IList)o[0])),F);
_operator(S("set_value_of"),Variables.class.getMethod("setValueOf",SC,GamaSolution.class,GamaVariable.class),null,AI,LI,F,-13,1,-13,-13,(s,o)->Variables.setValueOf(s,((GamaSolution)o[0]),((GamaVariable)o[1])),F);
_operator(S("bool_var"),Variables.class.getMethod("boolVar",SC,GamaProblem.class,S),null,AI,GamaVariable.class,F,-13,-13,-13,-13,(s,o)->Variables.boolVar(s,((GamaProblem)o[0]),((String)o[1])),F);
_operator(S("bool_vars"),Variables.class.getMethod("boolVars",SC,GamaProblem.class,S,i),null,AI,LI,F,-13,776002,-13,-13,(s,o)->Variables.boolVars(s,((GamaProblem)o[0]),((String)o[1]),asInt(s,o[2])),F);
_operator(S("variable_named"),Variables.class.getMethod("variableNamed",SC,GamaProblem.class,S),null,AI,GamaVariable.class,F,-13,-13,-13,-13,(s,o)->Variables.variableNamed(s,((GamaProblem)o[0]),((String)o[1])),F);
_operator(S("value_of"),Variables.class.getMethod("valueOf",SC,GamaSolution.class,GamaVariable.class),null,AI,I,F,-13,-13,-13,-13,(s,o)->Variables.valueOf(s,((GamaSolution)o[0]),((GamaVariable)o[1])),F);
_operator(S("mod_var"),Variables.class.getMethod("modVar",SC,GamaVariable.class,i),null,AI,GamaVariable.class,F,-13,-13,-13,-13,(s,o)->Variables.modVar(s,((GamaVariable)o[0]),asInt(s,o[1])),F);
_operator(S("abs_var"),Variables.class.getMethod("absVar",SC,GamaVariable.class),null,AI,GamaVariable.class,F,-13,-13,-13,-13,(s,o)->Variables.absVar(s,((GamaVariable)o[0])),F);
_operator(S("arg_max_var"),Variables.class.getMethod("argMaxVar",SC,LI),null,AI,GamaVariable.class,F,-13,-13,-13,-13,(s,o)->Variables.argMaxVar(s,((IList)o[0])),F);
_operator(S("min_var"),Variables.class.getMethod("minVar",SC,LI),null,AI,GamaVariable.class,F,-13,-13,-13,-13,(s,o)->Variables.minVar(s,((IList)o[0])),F);
_operator(S("scale_var"),Variables.class.getMethod("scaleVar",SC,GamaVariable.class,i),null,AI,GamaVariable.class,F,-13,-13,-13,-13,(s,o)->Variables.scaleVar(s,((GamaVariable)o[0]),asInt(s,o[1])),F);
_operator(S("real_var"),Variables.class.getMethod("realVar",SC,GamaProblem.class,S,d,d),null,AI,GamaVariable.class,F,-13,-13,-13,-13,(s,o)->Variables.realVar(s,((GamaProblem)o[0]),((String)o[1]),asFloat(s,o[2]),asFloat(s,o[3])),F);
_operator(S("int_vars"),Variables.class.getMethod("intVars",SC,GamaProblem.class,S,i,d,d),null,AI,LI,F,-13,776002,-13,-13,(s,o)->Variables.intVars(s,((GamaProblem)o[0]),((String)o[1]),asInt(s,o[2]),asFloat(s,o[3]),asFloat(s,o[4])),F);
_operator(S("int_var"),Variables.class.getMethod("intVar",SC,GamaProblem.class,S,d,d),null,AI,GamaVariable.class,F,-13,-13,-13,-13,(s,o)->Variables.intVar(s,((GamaProblem)o[0]),((String)o[1]),asFloat(s,o[2]),asFloat(s,o[3])),F);
_operator(S("count_var"),Variables.class.getMethod("countVar",SC,LI,i),null,AI,GamaVariable.class,F,-13,-13,-13,-13,(s,o)->Variables.countVar(s,((IList)o[0]),asInt(s,o[1])),F);
_operator(S("sum_var"),Variables.class.getMethod("sumVar",SC,LI),null,AI,GamaVariable.class,F,-13,-13,-13,-13,(s,o)->Variables.sumVar(s,((IList)o[0])),F);
}
}