source.. = src/,\
           gaml/
output.. = bin/
jre.compilation.profile = JavaSE-25
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               models/,\
               native/,\
               lib/choco-solver-6.0.1-light.jar,\
               lib/jna-5.18.1.jar
javacDefaultEncoding.. = UTF-8
